/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pepoc_androidnewtechnique_jni_test */

#ifndef _Included_com_pepoc_androidnewtechnique_jni_test
#define _Included_com_pepoc_androidnewtechnique_jni_test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pepoc_androidnewtechnique_jni_test
 * Method:    helloJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_pepoc_androidnewtechnique_jni_test_helloJni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
